import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import s from '@/styles/Home.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Currency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={s.main}>
        <div className="center">

        </div>
      </main>
    </>
  )
}
